// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTcuVn1u2bsa2DhimwgxG5v_p9t1lxqf0',
    appId: '1:563525324146:web:c2788230ad4c03378021eb',
    messagingSenderId: '563525324146',
    projectId: 'relaxtik',
    authDomain: 'relaxtik.firebaseapp.com',
    storageBucket: 'relaxtik.appspot.com',
    measurementId: 'G-BJ38PG3BB1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_ww-fojVYX0KRPo4F7rnpOTaR-s8vbCE',
    appId: '1:563525324146:android:a3c7ef4be1b2cb308021eb',
    messagingSenderId: '563525324146',
    projectId: 'relaxtik',
    storageBucket: 'relaxtik.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCETqKVGrfFFd2zClvuKL6Z4GinKg0uo00',
    appId: '1:563525324146:ios:e465f9e7b5366ae88021eb',
    messagingSenderId: '563525324146',
    projectId: 'relaxtik',
    storageBucket: 'relaxtik.appspot.com',
    iosClientId:
        '563525324146-a5b3tl3pi88105vbr10pglp4ndgibffn.apps.googleusercontent.com',
    iosBundleId: 'com.example.relaxTik',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCETqKVGrfFFd2zClvuKL6Z4GinKg0uo00',
    appId: '1:563525324146:ios:c14d1d517d210cbc8021eb',
    messagingSenderId: '563525324146',
    projectId: 'relaxtik',
    storageBucket: 'relaxtik.appspot.com',
    iosClientId:
        '563525324146-t40318bav5n2es2c87crccauufl0nrtn.apps.googleusercontent.com',
    iosBundleId: 'com.example.relaxTik.RunnerTests',
  );
}
